version: "3.8"
services:
  superhero:
    build:
      context: ./
      dockerfile: Dockerfile
    image: superheroe:v1
    ports:
      - "8080:8080"
    restart: always
    networks:
      - w2m
networks:
  w2m:
